/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: prologue.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @prologue: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly CradleCustomMacros macros1;
	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros2;

	@prologue()
	{
		this.StartPassage = "Landing";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new CradleCustomMacros() { Story = this };
		macros2 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Landing

	void passage1_Init()
	{
		this.Passages[@"Landing"] = new StoryPassage(@"Landing", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		macros1.dlgAbove("Derek");
		yield return text("???");
		yield return lineBreak();
		macros1.dlgAbove("Ryan");
		yield return text("???");
		yield return lineBreak();
		macros1.dlg("Derek");
		yield return text("This is where they dropped us! I curse them all! That girl deserves this punishem" +
		    "ent, not us!");
		yield return lineBreak();
		macros1.dlg("Ryan");
		yield return text("I\'m convinced Alexandra didn\'t purposely commit the terraforming directives to th" +
		    "is planet.");
		yield return lineBreak();
		macros1.dlg("Ryan");
		yield return text("Regardless, we need to find clothing and shelter or we are going to freeze to dea" +
		    "th.");
		yield return lineBreak();
		macros1.dlg("Derek");
		yield return text("!@#$, right... looks like the landing caused some collateral damage, let\'s grab t" +
		    "hose garments until we find something better.");
		yield return lineBreak();
		macros1.addArmor("Derek","cloth");
		yield return lineBreak();
		macros1.addArmor("Ryan","cloth");
		yield return lineBreak();
		macros1.dlg("Ryan");
		yield return text("let\'s go.");
		yield return lineBreak();
		macros1.addArmor("Richard","Big Sword");
		yield return lineBreak();
		macros1.addArmor("Dave","Big Sword");
		yield break;
	}


}